### ISSUE TITLE
Tech Reborn ores apearing in Age 2

### ISSUE THREAD

**Issue by harmor** [TheQuantumGeneral/Quaesitum#34]
I unlocked Age 2 and went mining for copper and tin and came across Tech Reborn ores that I don't have access to until Age 4.

**Comment by TheQuantumGeneral** [comment]
I realised in 2.4 that Tech Reborn ores were generating Copper, Tin, Silver and lead. I disabled the tech reborn versions from spawning to prevent double up and also unstaged the tech reborn variants.

This will be fixed in 2.6

**Comment by TheQuantumGeneral** [comment]
fixed in 2.6
