### ISSUE TITLE
Bees not showing in JEI

### ISSUE THREAD

**Issue by harmor** [TheQuantumGeneral/Quaesitum#35]
I've unlocked Age 2 and have access to Forestry machines but there are no results when I search for "drone" or "princess".

**Comment by TheQuantumGeneral** [comment]
I'll fix this for 2.6 but in the meantime try opening JEI settings, turning on Hide Mode, unchecking the bees and turning Hide Mode back off. They dont obey Game Stages very well

**Comment by TheQuantumGeneral** [comment]
fixed in 2.6
