### ISSUE TITLE
Game crashing to main menu

### ISSUE THREAD

**Issue by harmor** [TheQuantumGeneral/Quaesitum#37]
When I try and load up my world I get an "Closed Channel Exception" error.
Here is s bug report https://pastebin.com/KyiCghQ1

**Comment by TheQuantumGeneral** [comment]
Try going into the config folder, the forge.cfg file and setting these settings.

    # Set this to true to remove any Entity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringEntities=false

    # Set this to true to remove any TileEntity that throws an error in its update method instead of closing the server and reporting a crash log. BE WARNED THIS COULD SCREW UP EVERYTHING USE SPARINGLY WE ARE NOT RESPONSIBLE FOR DAMAGES.
    B:removeErroringTileEntities=false

both to true

**Comment by harmor** [comment]
I'm sorry but that didn't work.

**Comment by TheQuantumGeneral** [comment]
If this is still an issue let me know but it should be long since fixed.
